// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPECI.Data.Context;

#nullable disable

namespace SistemaPECI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250626152722_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SistemaPECI.Data.Entidades.Departamento", b =>
                {
                    b.Property<int>("IDDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDDepartamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("SistemaPECI.Data.Entidades.Persona", b =>
                {
                    b.Property<int>("IDPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDPersona");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("SistemaPECI.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IDDepartamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDPersona")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUsuario");

                    b.HasIndex("IDDepartamento");

                    b.HasIndex("IDPersona");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaPECI.Data.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemaPECI.Data.Entidades.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IDDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPECI.Data.Entidades.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IDPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
